---
- hosts: tor-fleet-managed
  vars:
    contact_info: "email:tor[]shadowbrokers.eu url:shadowbrokers.eu proof:dns-rsa btc:bc1qu9m2sy836pmyku0t3vnmpjxfjds8p2x5psyl6y ciissversion:2"
    tor_contact_email: tor@shadowbrokers.eu
    hostname: "{{ inventory_hostname }}"
    ipv6_enabled: "{{ ipv6_enabled_conf | default('yes') }}"
    tor_exit_enabled: "{{ tor_exit_enabled_conf | default('no') }}"
    kilobytes_burst: "{{ kilobytes_burst_conf | default('') }}"
    kilobytes_rate: "{{ kilobytes_rate_conf | default('') }}"
  roles:
    - setup-manjaro-user
    - setup-apparmor
    - restrict-kernel
    - setup-dns
    - install-and-configure-tor
    - install-netdata-agent
    - set-ssh-config #any reboots after this role, will fail during very first setup with root user
    - get-node-hash
