---
- hosts: testnode
  vars:
    contact_info: cozybear-dev <tor(@)shadowbrokers(.)eu>
    tor_contact_email: tor@shadowbrokers.eu
    hostname: "{{ inventory_hostname }}"
    ipv6_enabled: "{{ ipv6_enabled_conf | default('yes') }}"
    tor_exit_enabled: "{{ tor_exit_enabled_conf | default('no') }}"
    kilobytes_burst: "{{ kilobytes_burst_conf | default('') }}"
    kilobytes_rate: "{{ kilobytes_rate_conf | default('') }}"
  roles:
    - setup-manjaro-user
    - set-ssh-config 