---
- hosts: testnode
  vars:
    contact_info: "email:tor[]shadowbrokers.eu - testing automation"
    tor_contact_email: tor@shadowbrokers.eu
    hostname: "{{ inventory_hostname }}"
    ipv6_enabled: "{{ ipv6_enabled_conf | default('yes') }}"
    tor_exit_enabled: "{{ tor_exit_enabled_conf | default('no') }}"
    kilobytes_burst: "{{ kilobytes_burst_conf | default('') }}"
    kilobytes_rate: "{{ kilobytes_rate_conf | default('') }}"
  roles:
    # - setup-manjaro-user
    # - setup-apparmor
    # - restrict-kernel
    - setup-dns
    # - install-and-configure-tor
    # - install-netdata-agent
    # - set-ssh-config #any reboots after this role, will fail during very first setup with root user
    # - get-node-hash
