---
- name: Ensure torproject gpg key is installed (A3C4F0F979CAA22CDBA8F512EE8CBC9E886DDD89) #credits; https://github.dev/nusenu/ansible-relayor
  become: yes
  apt_key:
    url: https://deb.torproject.org/torproject.org/A3C4F0F979CAA22CDBA8F512EE8CBC9E886DDD89.asc
    id: A3C4F0F979CAA22CDBA8F512EE8CBC9E886DDD89
    state: present
    keyring: /usr/share/keyrings/deb.torproject.org-keyring.gpg
- name: Ensure Tor sources list is non-existent
  become: yes
  ansible.builtin.file:
    path: /etc/apt/sources.list.d/tor.list  
    state: absent
- name: Add Tor repositories
  become: yes
  ansible.builtin.apt_repository:
    repo: "{{ item.repo }}"
    state: present
    filename: tor
  loop:
    - repo: "deb [signed-by=/usr/share/keyrings/deb.torproject.org-keyring.gpg] https://deb.torproject.org/torproject.org {{ ansible_distribution_release }} main"
    - repo: "deb-src [signed-by=/usr/share/keyrings/deb.torproject.org-keyring.gpg] https://deb.torproject.org/torproject.org {{ ansible_distribution_release }} main"