---
- name: Install apparmor packages
  become: yes
  ansible.builtin.apt:
    name: "{{ item.package }}"
    state: present
    update_cache: yes
  loop:
    - package: apparmor
    - package: apparmor-utils
- name: Enable apparmor in grub
  become: yes
  lineinfile:
    line: "GRUB_CMDLINE_LINUX_DEFAULT=\"quiet security=apparmor apparmor=1\""
    regexp: "GRUB_CMDLINE_LINUX_DEFAULT"
    path: /etc/default/grub
  register: grub_change
- name: update grub
  become: yes
  shell: update-grub
  when: grub_change.changed
- name: Reboot
  become: yes
  reboot:
    msg: "Reboot initiated by Ansible as required"
    connect_timeout: 5
    reboot_timeout: 300
    pre_reboot_delay: 0
    post_reboot_delay: 30
    test_command: uptime
  when: grub_change.changed