---
- name: Install useful packages
  become: true
  ansible.builtin.apt:
    name: "{{ item.package }}"
    state: present
    update_cache: yes
  loop:
    - package: sudo
    - package: htop
- name: Create manjaro user
  become: true
  ansible.builtin.user:
    name: manjaro
    state: present
    password: "{{ lookup('community.general.bitwarden', 'manjaro-user-passwd-tor-fleet', field='password')[0] | password_hash }}"
    shell: /bin/bash
    group: sudo
- name: Set authorized key (yubikey 2fa) for manjaro user
  become: true
  ansible.posix.authorized_key:
    user: manjaro
    state: present
    exclusive: true
    key: sk-ssh-ed25519@openssh.com AAAAGnNrLXNzaC1lZDI1NTE5QG9wZW5zc2guY29tAAAAIDbXa6BWHM2avjHZlCzPfnYt/5we+WsdgN9asF9FS9DRAAAABHNzaDo=
- name: Disable root user
  become: true
  ansible.builtin.user:
    name: root
    state: present
    password_lock: true
    shell: "/sbin/nologin"