---
- name: Harden SSH configuration
  become: true
  lineinfile:
    line: "{{ item.line }}"
    regexp: "{{ item.regexp }}"
    path: /etc/ssh/sshd_config
  loop:
    - line: PermitRootLogin no
      regexp: ^PermitRootLogin
    - line: PubkeyAuthentication yes
      regexp: ^PubkeyAuthentication
    - line: PasswordAuthentication no
      regexp: ^PasswordAuthentication
    - line: UsePAM no
      regexp: ^UsePAM
    - line: LogLevel VERBOSE
      regexp: ^#LogLevel
    - line: GSSAPIAuthentication no
      regexp: ^#GSSAPIAuthentication
    - line: AllowAgentForwarding no
      regexp: ^#AllowAgentForwarding
    - line: AllowTcpForwarding no
      regexp: ^#AllowTcpForwarding
    - line: ClientAliveCountMax 2
      regexp: ^#ClientAliveCountMax
    - line: MaxAuthTries 3
      regexp: ^#MaxAuthTries
    - line: MaxSessions 2
      regexp: ^#MaxSessions
    - line: GatewayPorts no
      regexp: ^#GatewayPorts
    - line: TCPKeepAlive yes
      regexp: ^#TCPKeepAlive
  register: ssh_config
- name: Restart SSH service
  become: true
  ansible.builtin.service:
    name: ssh
    state: restarted
  when: ssh_config.changed