---
- name: Get running services
  ansible.builtin.service_facts:
- name: Netdata agent installation
  become: yes
  shell: wget -O /tmp/netdata-kickstart.sh https://my-netdata.io/kickstart.sh && sh /tmp/netdata-kickstart.sh --non-interactive --stable-channel --claim-token {{ lookup('community.general.bitwarden', 'netdata-claim-token', field='password')[0] }} --claim-rooms {{ lookup('community.general.bitwarden', 'netdata-claim-room', field='password')[0] }} --claim-url https://app.netdata.cloud
  when: ansible_facts.services["netdata.service"] is not defined